=== appfs/appfs/02_Exercise/measured-1-1-0.xsd
<?xml version="1.0" encoding="UTF-8"?>

<!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->
<!--                                                                                     -->
<!-- This file belongs to a first specification for the KWPT data interface              -->
<!-- Mathematical modelling, simulation, and optimization in the context of gas networks -->
<!--                                                                                     -->
<!-- Copyright (C) 17.11.2016                                                            -->
<!-- Developed by: Zuse Institute Berlin                                                 -->
<!-- Contact: Thorsten Koch (koch@zib.de)                                                --> 
<!-- All rights reserved.                                                                -->
<!--                                                                                     -->
<!-- Author: Oliver Kunst                                                                -->
<!--                                                                                     -->
<!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
  xmlns:framework="http://gaslab.zib.de/Framework" xmlns="http://gaslab.zib.de/kwpt/measured"
  xmlns:prog="http://gaslab.zib.de/kwpt/prognosis"
  targetNamespace="http://gaslab.zib.de/kwpt/measured" version="1.1.0">


  <xs:import namespace="http://gaslab.zib.de/Framework" schemaLocation="Framework-1-1-0.xsd"/>
  <xs:import namespace="http://gaslab.zib.de/kwpt/prognosis" schemaLocation="prognosis-1-1-0.xsd"/>
  
  <xs:element name="measured">
    <xs:complexType>
      <xs:complexContent>
        <xs:extension base="framework:rootBaseType">
          <xs:sequence>
            <xs:element ref="gasDay"/>
          </xs:sequence>          
        </xs:extension>
      </xs:complexContent>
    </xs:complexType>
  </xs:element>

  <xs:element name="gasDay">
    <xs:complexType>
      <xs:annotation>
        <xs:documentation>
          A list of boundary nodes with measured values.
        </xs:documentation>
      </xs:annotation>
      <xs:complexContent>
        <xs:extension base="framework:gasDayType">
          <xs:sequence>
            <xs:element ref="boundaryNode" minOccurs="0" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:extension>
      </xs:complexContent>
    </xs:complexType>
  </xs:element>

  <xs:element name="boundaryNode">
    <xs:annotation>
      <xs:documentation>
        Measured data for a single boundary node.
      </xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="time" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute name="id" type="framework:ambiguousIdentifier" use="required"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="time">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="amountOfPower"/>
        <xs:choice>
          <xs:element ref="measuredPressure"/>
          <xs:sequence>
            <xs:element ref="simulatedPressure"/>
            <xs:element ref="measuredPressure" minOccurs="0"/>
          </xs:sequence>
        </xs:choice>

      </xs:sequence>
      <xs:attribute name="hour" use="required">
        <xs:annotation>
          <xs:documentation>
            The hour of the gas day (1-25).
          </xs:documentation>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:positiveInteger">
            <xs:maxInclusive value="25"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="minute" use="required">
        <xs:annotation>
          <xs:documentation>
            The minute within the hour (minute 0) up to 59 minutes.
          </xs:documentation>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:nonNegativeInteger">
            <xs:maxInclusive value="59"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>


  <xs:element name="amountOfPower">
    <xs:annotation>
      <xs:documentation>The type for the amount power.</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:complexContent>
        <xs:extension base="framework:powerType">
          <xs:attribute  name="dataProcessingInformation" type="prog:processedInformationType">
            <xs:annotation>
              <xs:documentation>This type supports additional information to the amount of power. This may be useful to assign processing information to the data.</xs:documentation>              
            </xs:annotation>
          </xs:attribute>
        </xs:extension>
      </xs:complexContent>
    </xs:complexType>
  </xs:element>

  <xs:complexType name="measuredPressureType">
    <xs:annotation>
      <xs:documentation>This type supports additional information to the pressure. This may be useful to assign processing information to the data.</xs:documentation>
    </xs:annotation>
    <xs:complexContent>
      <xs:extension base="framework:pressureType">
        <xs:attribute name="dataProcessingInformation" type="prog:processedInformationType">
          <xs:annotation>
            <xs:documentation>Any processing information can be stored.</xs:documentation>
          </xs:annotation>
        </xs:attribute>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:element name="measuredPressure" type="measuredPressureType">
    <xs:annotation>
      <xs:documentation>The pressure measured on the entry / exit.
      </xs:documentation>
    </xs:annotation>
  </xs:element>

  <xs:element name="simulatedPressure" type="measuredPressureType">
    <xs:annotation>
      <xs:documentation>The pressure simulated on the entry / exit. Which may have significant errors.
      </xs:documentation>
    </xs:annotation>
  </xs:element>
</xs:schema>

=== appfs/appfs/02_Exercise/example.measured-1-1-0.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->
<!--                                                                                     -->
<!-- This file belongs to a first specification for the KWPT data interface              -->
<!-- Mathematical modelling, simulation, and optimization in the context of gas networks -->
<!--                                                                                     -->
<!-- Copyright (C) 17.11.2016                                                            -->
<!-- Developed by: Zuse Institute Berlin                                                 -->
<!-- Contact: Thorsten Koch (koch@zib.de)                                                --> 
<!-- All rights reserved.                                                                -->
<!--                                                                                     -->
<!-- Author: Oliver Kunst                                                                -->
<!--                                                                                     -->
<!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->

<measured xmlns="http://gaslab.zib.de/kwpt/measured"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://gaslab.zib.de/kwpt/measured ../schemes/measured-1-1-0.xsd"
    interfaceVersion="1.1.0"  source="MAG example">
    <gasDay date="2016-06-06" gasDayLengthInHours="24" gasDayStartHourInUTC="4">
        
        <!-- Die gemessenen Werte beginnen mit der ersten Stunde des Gastages -->
        <boundaryNode id="Entry1">
            <time hour="1" minute="0">
                <amountOfPower unit="MW" value="1000"/>
                <simulatedPressure unit="bar" value="55"/>
            </time>
            <!-- Es koennen unterstuendliche Werte gesetzt werden -->
            <time hour="1" minute="30">
                <amountOfPower unit="MW" value="1035"/>
                <simulatedPressure unit="bar" value="53"/>
            </time>
            <time hour="2" minute="0">
                <amountOfPower unit="MW" value="1100"/>
                <simulatedPressure unit="bar" value="50"/>
            </time>
            
            <!-- hier wuerden weitere Eitnraege folgen -->
        </boundaryNode>


        <!-- Wenn an einem Knoten der Druck gemessen wurde, so laesst sich auch das hinterlegen-->
        <boundaryNode id="Entry2">
            <time hour="1" minute="0">
                <amountOfPower unit="MW" value="900"/>
                <measuredPressure unit="bar" value="53.6"/>
            </time>
            <time hour="2" minute="0">
                <amountOfPower unit="MW" value="990"/>
                <measuredPressure unit="bar" value="51.9"/>
            </time>
            <time hour="3" minute="0">
                <amountOfPower unit="MW" value="960"/>
                <simulatedPressure unit="bar" value="53.1"/>
            </time>
            
            <!-- hier wuerden weitere Eitnraege folgen -->
        </boundaryNode>


        <!-- Wenn an einem Knoten der Druck gemessen wurde, so laesst sich auch das hinterlegen-->
        <boundaryNode id="TheExit">
            <time hour="1" minute="0">
                <amountOfPower unit="MW" value="-1800"/>
                <simulatedPressure unit="bar" value="55"/>
            </time>
            <time hour="2" minute="0">
                <amountOfPower unit="MW" value="-1690"/>
                <simulatedPressure unit="bar" value="58"/>
            </time>

            <time hour="3" minute="0">
                <amountOfPower unit="MW" value="-2000"/>
                <simulatedPressure unit="bar" value="60"/>
            </time>
            
            <!-- hier wuerden weitere Eitnraege folgen -->
        </boundaryNode>
        
    </gasDay>
</measured>
